
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: covidmap-server
  namespace: covidmap
  labels:
    environment: production
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 120
  sessionAffinity:
    affinityType: COOKIE
    affinityCookieTtlSec: 300
  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: covidmap-redirect
  namespace: covidmap
  labels:
    environment: production
spec:
  timeoutSec: 10
  connectionDraining:
    drainingTimeoutSec: 30
  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
