
apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: covidmap
data:
  tls.key: LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdncWhrak9QUU1CQnc9PQotLS0tLUVORCBFQyBQQVJBTUVURVJTLS0tLS0KLS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNCMHpVNlB2elo0cUc0bUZPdjlIOFZDMlo4RTI4SGJaYVZ1UFRrU29uenRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFU0txMCs5YWtCWkl0TWRwTGVyeTN0K1YveHczdnIwNVRQakpzYVlvSE9Cb0FndjdGeWczZgpBRUlOTi91TEhIMEFPSEJtRjBQd3Nkb3BzVkZpcUxScXl3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFNQ0NRQ2VQNk8xdjlSM1RqQUpCZ2NxaGtqT1BRUUJNSUdHTVFzd0NRWURWUVFHRXdKVlV6RVQKTUJFR0ExVUVDQXdLUTJGc2FXWnZjbTVwWVRFUk1BOEdBMVVFQnd3SVYyOXZaSE5wWkdVeEVqQVFCZ05WQkFvTQpDVU5QVmtsRUlFMWhjREViTUJrR0ExVUVDd3dTUkdsbmFYUmhiQ0JQY0dWeVlYUnBiMjV6TVI0d0hBWURWUVFECkRCVnpZVzVrWW05NExtTnZkbWxrYldGd0xteHBibXN3SGhjTk1qQXdNekl5TWpNd05qRTFXaGNOTWpFd016SXkKTWpNd05qRTFXakNCaGpFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RVRBUApCZ05WQkFjTUNGZHZiMlJ6YVdSbE1SSXdFQVlEVlFRS0RBbERUMVpKUkNCTllYQXhHekFaQmdOVkJBc01Fa1JwCloybDBZV3dnVDNCbGNtRjBhVzl1Y3pFZU1Cd0dBMVVFQXd3VmMyRnVaR0p2ZUM1amIzWnBaRzFoY0M1c2FXNXIKTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFU0txMCs5YWtCWkl0TWRwTGVyeTN0K1YveHczdgpyMDVUUGpKc2FZb0hPQm9BZ3Y3RnlnM2ZBRUlOTi91TEhIMEFPSEJtRjBQd3Nkb3BzVkZpcUxScXl6QUpCZ2NxCmhrak9QUVFCQTBjQU1FUUNJRzF5ZmtmYmRWUHBBNEM0ZGZBa0Rkbk1rYWZuRDdTWmcwSzFqY3FHVlRUL0FpQmMKaHh0YzVaSnp1MzlSa2N0cGx5QStvZHNOQWk5b2gzakw3MkRpVUhRMW1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: envoy-hpa
  namespace: covidmap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: covidmap
  labels:
    environment: production
spec:
  # -- Replication ----------------------------------------------------------- #
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: covidmap
      role: gateway
      environment: production

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: "30%"

  # -- Timeouts -------------------------------------------------------------- #
  minReadySeconds: 10
  progressDeadlineSeconds: 300

  template:
    metadata:
      labels:
        app: covidmap
        role: gateway
        environment: production
    spec:
      # -- Networking --------------------------------------------------------- #
      dnsPolicy: ClusterFirst

      # -- Placement ---------------------------------------------------------- #
      tolerations:
        - key: role
          operator: Equal
          value: app
        - key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor

      affinity:
        # Schedule away from other gateway pods.
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - gateway
                topologyKey: kubernetes.io/hostname

      # -- Containers --------------------------------------------------------- #
      containers:
        ## Container: Gateway Proxy (Envoy)
        - name: envoy
          image: us.gcr.io/covid-impact-map/gateway:v7c
          ports:
            - name: tls-gateway
              containerPort: 8443
            - name: http-health
              containerPort: 8090
            - name: http-admin
              containerPort: 9901
          resources:
            requests:
              cpu: "0.2"
              memory: "64Mi"
            limits:
              cpu: "0.4"
              memory: "256Mi"
          volumeMounts:
            - name: tls
              mountPath: /etc/ssl/envoy
          readinessProbe:
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 2
            initialDelaySeconds: 5
            httpGet:
              path: /healthz
              port: 8090
          livenessProbe:
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 2
            httpGet:
              path: /healthz
              httpHeaders:
                - name: x-envoy-livenessprobe
                  value: healthz
              port: 8090
            initialDelaySeconds: 10
      volumes:
        - name: tls
          secret:
            secretName: tls
